name: crop_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - requests=2.24.0
  - pyarrow
  - jupyter
  - pandas
  - scikit-learn
  - seaborn
  - matplotlib
  - numpy
  - pip:
    - mlflow==2.8.1
    - wandb==0.16.0
